name: Deploy to Firebase Hosting on PR
'on': pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Create env file
        run: |
          cat << EOF > .env
          VITE_apiKey=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_authDomain=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_projectId=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_storageBucket=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_messagingSenderId=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_appId=${{ secrets.VITE_FIREBASE_APP_ID }}
          EOF

      - name: Build
        run: npx quasar build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIVIDIS_75984 }}'
          projectId: dividis-75984
